#!/usr/bin/env sh

# PREPARE
herbstclient emit_hook reload
herbstclient keyunbind --all
mod=Mod5
super=Mod4

# FAKEFULLSCREEN
herbstclient keybind $super-x substitute FSRESTORE clients.focus.fullscreen chain , fullscreen on , attr clients.focus.ewmhrequests off , attr clients.focus.ewmhnotify toggle , spawn herbstclient fullscreen FSRESTORE

# KILL
herbstclient keybind $mod-Shift-q quit
herbstclient keybind $mod-Shift-r reload
herbstclient keybind $mod-c close
herbstclient keybind $mod-u close
herbstclient keybind $super-q close

# LAYOUTS
herbstclient keybind $super-a use_index +1
herbstclient keybind $mod-m spawn ~/.config/herbstluftwm/maximize.sh
herbstclient keybind $super-c spawn ~/.config/herbstluftwm/maximize.sh
# herbstclient keybind $mod-p pseudotile toggle
# herbstclient keybind $super-w pseudotile toggle
herbstclient set default_frame_layout 2
herbstclient set tree_style '╾│ ├└╼─┐'

# MONITORS
herbstclient detect_monitors
herbstclient keybind $mod-BackSpace cycle_monitor

# MOUSE
herbstclient mouseunbind --all
herbstclient mousebind $super-Button1 resize
herbstclient set focus_follows_mouse 1

# MOVING
herbstclient keybind $mod-Shift-h shift left
herbstclient keybind $mod-Shift-j shift down
herbstclient keybind $mod-Shift-k shift up
herbstclient keybind $mod-Shift-l shift right
herbstclient keybind $super-e shift left
herbstclient keybind $super-r shift right

# NAVIGATION
herbstclient keybind $mod-l cycle_frame
herbstclient keybind $mod-k cycle -1
herbstclient keybind $mod-j cycle +1

# RESIZING
resizestep=0.015
herbstclient keybind $mod-Control-h resize left $resizestep
herbstclient keybind $mod-Control-l resize right $resizestep

# RULES
herbstclient unrule -F
herbstclient rule focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class~.* index=0
herbstclient rule class~'Nemo|jetbrains-.*|.*-256color' index=1
herbstclient rule class='java-lang-Thread' pseudotile=on index=1
herbstclient rule title~'Welcome.*' pseudotile=on index=1

# TAGS
herbstclient rename default 1
herbstclient add 2
herbstclient keybind $mod-Shift-o move_index +1
herbstclient keybind $mod-o use_index +1

# THEME
herbstclient attr theme.floating.reset 1
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.border_width 1
herbstclient set frame_bg_transparent 1
herbstclient set frame_border_width 0
herbstclient set frame_gap 0

# INIT
layout='(split horizontal:0.52:1 (clients max:0 0x1000003) (clients max:0 0xc00005))'
if herbstclient silent new_attr bool my_not_first_autostart ; then
    herbstclient load 1 "$layout"
    herbstclient load 2 "$layout"
    herbstclient pad 0 0 0 7 0
    herbstclient spawn bstatus
    herbstclient spawn "$BROWSER"
    herbstclient spawn "$TERMINAL"
    herbstclient spawn sxhkd
    herbstclient spawn xkbcomp ~/.config/xkb/xkeymap "$DISPLAY"
fi
herbstclient unlock
