#!/usr/bin/env sh

# PREPARE
herbstclient emit_hook reload
herbstclient keyunbind --all
mod=Mod5
super=Mod4

# COMMANDS
herbstclient keybind $mod-Return spawn st
herbstclient keybind $mod-f spawn rofi -combi-modi window,drun -show combi -me-select-entry '' -me-accept-entry 'MousePrimary'
herbstclient keybind $super-f spawn rofi -combi-modi window,drun -show combi -me-select-entry '' -me-accept-entry 'MousePrimary'
herbstclient keybind $super-Shift-e spawn pulsemixer --change-volume +4
herbstclient keybind $super-Shift-w spawn pulsemixer --change-volume -4
herbstclient keybind $super-e spawn light -A 8
herbstclient keybind $super-r spawn light -S 100
herbstclient keybind $super-w spawn light -U 8

# FAKEFULLSCREEN
herbstclient keybind $super-x substitute FSRESTORE clients.focus.fullscreen chain , fullscreen on , attr clients.focus.ewmhrequests off , attr clients.focus.ewmhnotify toggle , spawn herbstclient fullscreen FSRESTORE

# KILL
herbstclient keybind $mod-Shift-q quit
herbstclient keybind $mod-Shift-r reload
herbstclient keybind $mod-q close
herbstclient keybind $mod-u close
herbstclient keybind $super-q close

# LAYOUTS
herbstclient keybind $super-c cycle_layout 1 max vertical
herbstclient keybind $mod-n cycle_layout 1 max vertical
herbstclient keybind $super-a spawn /usr/share/doc/herbstluftwm/examples/maximize.sh
herbstclient keybind $mod-m spawn /usr/share/doc/herbstluftwm/examples/maximize.sh
herbstclient keybind $mod-p pseudotile toggle
herbstclient set default_frame_layout 2
herbstclient set tree_style '╾│ ├└╼─┐'

# MONITORS
herbstclient detect_monitors
herbstclient keybind $mod-BackSpace cycle_monitor

# MOUSE
herbstclient mouseunbind --all
herbstclient mousebind $super-Button1 resize
herbstclient set focus_follows_mouse 1

# MOVING
herbstclient keybind $mod-Shift-h shift left
herbstclient keybind $mod-Shift-j shift down
herbstclient keybind $mod-Shift-k shift up
herbstclient keybind $mod-Shift-l shift right

# NAVIGATION
herbstclient keybind $mod-l cycle_frame
herbstclient keybind $super-s cycle -1
herbstclient keybind $super-d cycle +1
herbstclient keybind $mod-k cycle -1
herbstclient keybind $mod-j cycle +1

# RESIZING
resizestep=0.02
herbstclient keybind $mod-Control-h resize left $resizestep
herbstclient keybind $mod-Control-l resize right $resizestep

# RULES
herbstclient unrule -F
herbstclient rule focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class~.* index=0
herbstclient rule class~'Nemo|jetbrains-.*|st-256color' index=1
herbstclient rule class~'java-lang-Thread' pseudotile=on index=1

# TAGS
herbstclient rename default 1
herbstclient add 2
herbstclient keybind $mod-Shift-o move_index +1
herbstclient keybind $mod-o use_index +1

# THEME
herbstclient attr theme.floating.reset 1
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.border_width 1
herbstclient set frame_bg_transparent 1
herbstclient set frame_border_width 0
herbstclient set frame_gap 0

# INIT DEFAULT LAYOUT
layout='(split horizontal:0.545000:1 (clients max:0 0x1000003) (clients max:0 0xc00005))'
if herbstclient silent new_attr bool my_not_first_autostart ; then
    herbstclient load 1 "$layout"
    herbstclient spawn "$BROWSER"
    herbstclient spawn "$TERMINAL"
    herbstclient pad 0 0 0 7 0
fi
herbstclient unlock
