#!/usr/bin/env sh

# DEFAULTS
alias df="df -h"
alias du="du -h"
alias fdisk="sudo fdisk"
alias gdisk="sudo gdisk"
alias grep="grep --color --exclude-dir=.*"
alias ls="ls -Ahv --color --group-directories-first"
alias lsblk="lsblk -o name,label,mountpoint,fstype,size"
alias mount="sudo mount"
alias pacman="doas pacman"
alias tree="tree -aCI '__pycache__|.git|*.aux|*.fdb_latexmk|*.fls|*.log|*.nav|*.snm|*.gz|*.toc' --dirsfirst --noreport"
alias umount="sudo umount"
alias watch="watch --color"

# CPM
alias x="cpm"
alias xc="cpm -c"
alias xd="cpm -d"
alias xm="cpm -m"
alias xp="cpm -p"

# BOOKMARKS - HIDDEN
path_bm="$HOME"/cloud/notes/bookmarks.sh
[ -r "$path_bm" ] && . "$path_bm"
alias bm="\$EDITOR \$path_bm && . \$path_bm"

# BOOKMARKS - FILES
alias fa="jumpopen \$DOTS aliases && . \$DOTS/aliases"
alias faa="jumpopen ~/projects/arch desktop.sh base.sh"
alias fb="jumpopen \$DOTS .bashrc && . \$DOTS/.bashrc"
alias fbl="\$EDITOR ~/.config/bashrc_local && . ~/.config/bashrc_local"
alias fgi="\$EDITOR \$(git rev-parse --show-toplevel)/.gitignore"
alias fgm="\$EDITOR \$(git rev-parse --show-toplevel)/.gitmodules"
alias fn="jumpopen \$DOTS nvim/init.vim"
alias fp="jumpopen \$DOTS .profile"
alias fr="\$EDITOR \$(git rev-parse --show-toplevel)/README.md"
alias fu="nvim +'h user-manual | winc o'"
alias fv="jumpopen ~/projects/vlugins README.md"
alias fx="jumpopen \$DOTS sx/sxrc"
f() { if [ -d "$1" ]; then cd "$1" || return; else "$OPENER" "$@"; fi }
jumpopen() { cd "$1" >/dev/null && shift && "$OPENER" "$@" ; }

# BOOKMARKS - DIRS
alias dl="cd ~/Downloads"
alias ja="cd ~/projects/arch"
alias jbi="cd \$HOME/.local/bin"
alias jca="cd \$XDG_CACHE_HOME"
alias jco="cd \$XDG_CONFIG_HOME"
alias jd="cd ~/projects/dotfiles"
alias jdf="cd ~/projects/dotfiles && f"
alias jj="cd ~/projects"
alias jjj="cd ~/projects && j"
alias js="cd ~/projects/scripts"
alias jsf="cd ~/projects/scripts && f"
alias jsh="cd \$XDG_DATA_HOME"
alias jt="cd ~/projects/st"
alias jv="cd ~/projects/vlugins"

# BOOKMARKS - NOTES
alias jn="cd ~/cloud/notes"
alias n="jumpopen ~/cloud/notes notes.md"
alias ni="jumpopen ~/cloud/notes ideas.md"

j() {
    dir=$1
    if [ $# = 0 ]; then
        dir=$(ffind -type d 2>/dev/null | fzf)
    elif [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    [ -n "$dir" ] && cd "$dir" || return
}

# CLOUD
alias jc="cd ~/cloud"
alias sn="rclone sync -P ~/cloud cloud:"
alias snn="rclone sync -P cloud: ~/cloud"

# GIT
k() { n=24; [ "$1" ] && n=$1; git log --all --graph --decorate --oneline --show-pulls -n"$n"; }
kcl() { git clone "$@" "$(xsel -b | head -n1)"; }
kg() { nvim +"Flog -search=$1"; }
krh() { n=1; [ "$1" ] && n=$1; git reset --hard HEAD~"$n"; }
ksf() { if [ $# = 0 ]; then git show | "$EDITOR"; else git show "$1" | "$EDITOR"; fi }

alias ka="git add"
alias kaa="git add --all"
alias kam="git commit --amend -v"
alias kap="git add -p"
alias kb="git branch -vv"
alias kba="git branch -avv"
alias kbd="git branch -D"
alias kbr="git remote -v | grep -P \(push\) | cut -d ' ' -f 1 | cut -f 2 | xargs -r \$BROWSER"
alias kd="git diff"
alias kfp="git format-patch --stdout HEAD^ >"
alias kk="nvim +Flog"
alias kr="cd \$(git rev-parse --show-toplevel)"
alias krv="git remote -v"
alias ks="git status -bs"
alias kt="git tag"

alias kc="git commit -v"
alias kca="git add --all && git commit -v"
alias kcp="git add --all && git commit -v && git push"
alias kcr="git commit -v -am tmp && git rebase -i HEAD~2"
alias kcrf="git commit -v -am tmp && git rebase -i HEAD~2 && git push -f"

alias ko="git checkout"
alias kop="git checkout -p"
alias kob="git checkout -b"
alias kom="git checkout master"

alias kf="git fetch"
alias kfr="git fetch \$(git remote | fzf)"
alias km="git merge"
alias kmm="git merge master"
alias kp="git push"
alias kpf="git push -f"
alias kpl="git pull"

alias kra="git rebase --abort"
alias krbr="git rebase -i --root"
alias krc="git rebase --continue"
alias krm="git rebase master"
krb() { n=16; [ "$1" ] && n=$1; git rebase -i HEAD~"$n"; }

alias kr.="git reset ."
alias krr="git reset --hard; git clean -f"
alias krs.="git reset --soft HEAD~1; git reset ."
alias krs="git reset --soft HEAD~1"
alias krv="git revert"

alias ksd="git stash drop"
alias ksl="git stash list"
alias ksp="git stash pop"
alias kst="git stash"

# MISC
alias a="execute"
alias as="echo Remapped to do nothing."
alias b="cd - >/dev/null && ls"
alias c="cd .."
alias clean="doas pacman -Rns \$(pacman -Qttdq); doas pacman -Sc; rm -fr \$XDG_CACHE_HOME/*; doas rm -fr /var/log/journal/*; rm -fr \$XDG_DATA_HOME/nvim/view/*"
alias da="d *"
alias dus="du -s"
alias e="\$EDITOR ."
alias g="grep -Rn"
alias gf="ffind | grep"
alias h="python"
alias i="pkg -i"
alias ig="iwctl station wlan0 get-networks"
alias ir="systemctl restart iwd.service"
alias is="iwctl station wlan0 scan"
alias l="preview"
alias lb="lsblk"
alias ll="ls -l"
alias lt="lint"
alias m="mmrdf"
alias o="autopen"
alias pa="patch -p1 <"
alias r="pkg -r"
alias re="sudo \$(fc -ln -1)"
alias s="echo \$(bstatus)% \| \$(pulsemixer --get-volume) \$(pulsemixer --get-mute) \| \$(date +%H:%M) \| \$(date +%d.%m.%y)"
alias sc="scrot -s"
alias td="tree -d"
alias tf="tree"
alias tmp="nvim +'set nospell' /tmp/scratch.md"
alias u="doas sh -c \"curl -s 'https://archlinux.org/mirrorlist/?country=DE&protocol=https&use_mirror_status=on' | sed -e s/^#Server/Server/ -e /^#/d > /etc/pacman.d/mirrorlist\" && paru"
alias v="pulsemixer"
ar() { dir="$(basename "$1").tar.gz"; [ $# -gt 1 ] && shift; tar -czvf "$dir" "$@"; }
cd() { builtin cd "$@" && ls; }
d() { if [ $# = 0 ]; then exit; else realpath -s "$@" | sed 's/.*/"&"/' | xargs rm -fr; ls; fi }
flash() { sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync; }
p() { if [ $# = 0 ]; then pwd | sed "s|$HOME|~|"; else cp -irv "$@"; fi }
y() { youtube-dl "$@" "$(xsel -b | head -n1)"; }

# TMUX
alias t="tmux new -A"
alias ta="tmux a -t"
alias tk="tmux kill-session -a"
alias tkt="tmux kill-session -t"
alias tl="tmux ls"
alias ts="tmux switch -t"
tt() { echo "$TMUX_PANE" > /tmp/tmuxsend; }

# VIM
vpa() {
    [ $# = 0 ] && url="$(xsel -b | head -n1)" || url="$1"
    name=$(echo "$url" | sed s/.git$// | sed s/.n*vim$// | sed 's/.*\///' | sed s/^n*vim-//)
    git submodule add --force --name "$name" "$url" "nvim/pack/plugins/opt/$name"
}
vpd() {
    [ $# = 0 ] && echo No submodule provided. && return
    git rm -f "nvim/pack/plugins/opt/$1"
    rm -fr ".git/modules/$1"
}

# WALLPAPERS
alias jwl="cd ~/cloud/pictures/wallpapers"
alias wd="wal -d"
alias wn="cd ~/cloud/pictures/wallpapers && wal"
