#!/usr/bin/env sh

# DEFAULTS
alias cp='cp -irv'
alias df="df -h"
alias du="du -h"
alias fdisk="sudo fdisk"
alias gdisk="sudo gdisk"
alias grep="grep --color --exclude-dir=.git"
alias ls="ls -Ahv --color --group-directories-first"
alias lsblk="lsblk -o name,label,mountpoint,fstype,size"
alias mkdir="mkdir -p"
alias mount="sudo mount"
alias mv="mv -iv"
alias pacman="sudo pacman"
alias rm="rm -fr"
alias tree="tree -aCI '__pycache__|.git|*.aux|*.fdb_latexmk|*.fls|*.log|*.nav|*.snm|*.gz|*.toc' --dirsfirst --noreport"
alias umount="sudo umount"
alias watch="watch --color"

# CPM
alias x="cpm"
alias xc="cpm -c"
alias xd="cpm -d"
alias xm="cpm -m"
alias xp="cpm -p"

# BOOKMARKS - HIDDEN
path_bm="$HOME"/cloud/bookmarks.sh
[ -r "$path_bm" ] && . "$path_bm"
alias fbm="\$EDITOR \$path_bm && . \$path_bm"

# BOOKMARKS - FILES
alias fa="jumpopen \$DOTS aliases && . \$DOTS/aliases"
alias faa="jumpopen ~/projects/arch desktop.sh base.sh"
alias fb="jumpopen \$DOTS .bashrc && . \$DOTS/.bashrc"
alias fbl="\$EDITOR ~/.config/bashrc_local && . ~/.config/bashrc_local"
alias fgi="\$EDITOR \$(git rev-parse --show-toplevel)/.gitignore"
alias fgm="\$EDITOR \$(git rev-parse --show-toplevel)/.gitmodules"
alias fn="jumpopen \$DOTS nvim/init.vim"
alias fp="jumpopen \$DOTS .profile"
alias fr="\$EDITOR \$(git rev-parse --show-toplevel)/README.md"
alias fx="jumpopen \$DOTS sx/sxrc"
alias n="\$EDITOR ~/cloud/notes"

f() {
    if [ -f "$1" ]; then
        "$OPENER" "$@" || return
    elif [ $# = 0 ]; then
        fzf | xargs -r "$OPENER"
    elif [ ! -f "$1" ]; then
        ffind -maxdepth 1 -type f | fzf --filter="$*" | head -n1 | xargs -r "$OPENER"
    fi
}
jumpopen() { cd "$1" >/dev/null && shift && "$OPENER" "$@" ; }

# BOOKMARKS - DIRS
alias dl="cd ~/Downloads"
alias ja="cd ~/projects/arch"
alias jbi="cd \$HOME/.local/bin"
alias jca="cd \$XDG_CACHE_HOME"
alias jco="cd \$XDG_CONFIG_HOME"
alias jd="cd ~/projects/dotfiles"
alias jdf="cd ~/projects/dotfiles && f"
alias jj="cd ~/projects"
alias js="cd ~/projects/scripts"
alias jsf="cd ~/projects/scripts && f"
alias jsh="cd \$XDG_DATA_HOME"
alias jsi="cd ~/projects/sites"
alias jt="cd ~/projects/st"

j() {
    if [ -d "$1" ]; then
        cd "$1" || return
    elif [ $# = 0 ]; then
        dir=$(ffind -type d 2>/dev/null | fzf)
    else
        dir=$(ffind -maxdepth 1 -type d 2>/dev/null | fzf --filter="$*" | head -n1)
    fi
    if [ -n "$dir" ]; then
        cd "$dir" || return
    fi
}

# CLOUD
alias jc="cd ~/cloud"
alias sn="rclone sync -P ~/cloud cloud:"
alias snn="rclone sync -P cloud: ~/cloud"

# GIT
k() { n=24; [ "$1" ] && n=$1; git log --all --graph --decorate --oneline --show-pulls -n"$n"; }
kcl() { git clone "$@" "$(xsel -b | head -n1)"; }
krh() { n=1; [ "$1" ] && n=$1; git reset --hard HEAD~"$n"; }
ksf() { if [ $# = 0 ]; then git show | $EDITOR; else git show "$1" | $EDITOR; fi }

alias ka="git add"
alias kaa="git add --all"
alias kam="git commit --amend -v"
alias kap="git add -p"
alias kb="git branch -vv"
alias kba="git branch -avv"
alias kbd="git branch -D"
alias kbr="git remote -v | grep -P \(push\) | cut -d ' ' -f 1 | cut -f 2 | xargs -r \$BROWSER"
alias kfp="git format-patch --stdout HEAD^ >"
alias ki="git init"
alias kii="git add --all && git commit -m 'Create repository'"
alias kr="cd \$(git rev-parse --show-toplevel)"
alias krm="git remote -v"
alias kt="git tag"

alias kc="git commit -v"
alias kca="git add --all && git commit -v"
alias kcp="git add --all && git commit -v && git push"
alias kcr="git commit -v -am tmp && git rebase -i HEAD~2"
alias kcrf="git commit -v -am tmp && git rebase -i HEAD~2 && git push -f"

alias kd="git diff"
alias kg="git log --color --oneline --grep"
alias kk="git log --all --graph --decorate --oneline --show-pulls"
alias kkk="git log --graph --decorate --oneline --show-pulls"
alias kl="git log --date=auto:human"
alias klg="git log --grep"
alias ks="git status -bs"
alias kso="git show"
alias kss="nvim +Flog"

alias ko="git checkout"
alias kop="git checkout -p"
alias kob="git checkout -b"
alias kom="git checkout master"

alias kf="git fetch"
alias kfr="git fetch \$(git remote | fzf)"
alias km="git merge"
alias kmm="git merge master"
alias kp="git push"
alias kpf="git push -f"
alias kpl="git pull"

alias kra="git rebase --abort"
alias krc="git rebase --continue"
krb() { n=16; [ "$1" ] && n=$1; git rebase -i HEAD~"$n"; }

alias krr="git reset --hard; git clean -f"
alias krs="git reset --soft"
alias krv="git revert"

alias ksd="git stash drop"
alias ksl="git stash list"
alias ksp="git stash pop"
alias kst="git stash"

# MISC
alias a="execute"
alias as="echo Remapped to do nothing."
alias b="cd - >/dev/null && ls"
alias c="cd .."
alias clean="sudo pacman -Rns \$(pacman -Qttdq); sudo pacman -Sc; rm -r \$XDG_CACHE_HOME/* sudo rm -fr /var/log/journal/*"
alias dus="du -s"
alias e="\$EDITOR ."
alias g="grep -Rn"
alias gf="ffind | grep"
alias h="python"
alias i="pkg -i"
alias ig="iwctl station wlan0 get-networks"
alias ir="systemctl restart iwd.service"
alias is="iwctl station wlan0 scan"
alias lb="lsblk"
alias ll="ls -l"
alias lt="lint"
alias m="mv"
alias o="autopen"
alias p="cp"
alias pa="patch -p1 <"
alias pm="pulsemixer"
alias pw="pwd | sed \"s|\$HOME|~|\""
alias r="pkg -r"
alias re="sudo \$(fc -ln -1)"
alias s="fg"
alias si="echo BATTERY: \"\$(bstatus)\"; echo TIME: \"\$(date +%H%M)\"; echo DATE: \"\$(date +%d.%m.%y)\""
alias td="tree -d"
alias tf="tree"
alias tmp="nvim +'set nospell' /tmp/scratch.md"
alias u="sudo sh -c \"curl -s 'https://www.archlinux.org/mirrorlist/?country=DE&protocol=https&use_mirror_status=on' | sed -e s/^#Server/Server/ -e /^#/d > /etc/pacman.d/mirrorlist\" && paru"
alias v="\$EDITOR"
ar() { dir="$(basename "$1").tar.gz"; [ $# -gt 1 ] && shift; tar -czvf "$dir" "$@"; }
cd() { builtin cd "$@" && ls; }
d() { if [ $# = 0 ]; then exit; else rm "$@"; fi }
flash() { sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync; }
y() { youtube-dl "$@" "$(xsel -b | head -n1)"; }

# MK
alias md="mkdir -p"
alias mf="touch"
mdj() { mkdir "$1" && cd "$1" || return; }
mfx() { touch "$1"; chmod +x "$1"; }

# PREVIEW
l() {
    if [ $# = 0 ] || [ -e "$1" ]; then
        preview "$1"
    else
        ffind -maxdepth 1 | fzf --filter="$*" | head -n1 | xargs -r preview
    fi
}

# TMUX
alias t="tmux new -A"
alias ta="tmux a -t"
alias tk="tmux kill-session -t"
alias tkk="tmux kill-session -a"
alias tl="tmux ls"
alias ts="tmux switch -t"
tt() { echo "$TMUX_PANE" > /tmp/tmuxsend; }

# VIM
vpa() {
    [ $# = 0 ] && url="$(xsel -b | head -n1)" || url="$1"
    name=$(echo "$url" | sed s/.git$// | sed s/.n*vim$// | sed 's/.*\///' | sed s/^n*vim-//)
    git submodule add --force --name "$name" "$url" "nvim/pack/plugins/opt/$name"
}
vpd() {
    [ $# = 0 ] && echo No submodule provided. && return
    git rm -f "nvim/pack/plugins/opt/$1"
    rm -fr ".git/modules/$1"
}
