#!/usr/bin/env sh

export PATH=$HOME/.local/bin:$PATH

export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CONFIG_DIRS=$XDG_CONFIG_HOME:/etc/xdg:$XDG_CONFIG_DIRS
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=$XDG_DATA_HOME:/usr/local/share:/usr/share:$XDG_DATA_DIRS
export XDG_SESSION_TYPE=x11

export CONFIG=$HOME/projects/config
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/settings.ini
export INPUTRC=$XDG_CONFIG_HOME/inputrc
export IPYTHONDIR=$XDG_CONFIG_HOME/ipython
export LESSHISTFILE=$XDG_CACHE_HOME/lesshst
export PYLINTHOME=$XDG_CACHE_HOME/pylint
export PYLINTRC=$XDG_CONFIG_HOME/pylintrc
export PYTHONSTARTUP=$XDG_CONFIG_HOME/pythonrc.py
export TERMINFO=$XDG_DATA_HOME/terminfo
export TERMINFO_DIRS=$TERMINFO:/usr/share/terminfo

export BROWSER=firefox
export EDITOR=nvim
export MANPAGER="nvim +Man!"
export OPENER=open
export TERMINAL=st
export VIEWER_IMG=gthumb
export VIEWER_MP3=$BROWSER
export VIEWER_PDF=$BROWSER
export VIEWER_VID=$BROWSER

export FZF_CTRL_T_OPTS="--select-1 --exit-0"
export FZF_DEFAULT_COMMAND="ffind -type f"
export FZF_DEFAULT_OPTS="--cycle --multi --reverse --preview-window border-sharp --tabstop=4 --tiebreak=begin,length,end,index --no-info --color=bg+:-1,fg+:-1,border:16,hl:1,hl+:1,prompt:4,pointer:2,marker:3,info:8"
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM=auto

# DEFAULTS
alias df="df -h"
alias du="du -h"
alias grep="grep --color --exclude-dir=.*"
alias ls="ls -Ahv --color --group-directories-first"
alias tree="tree -aCI '__pycache__|.git|*.aux|*.fdb_latexmk|*.fls|*.log|*.nav|*.snm|*.gz|*.toc' --dirsfirst --noreport"
alias watch="watch --color"

# CPM
alias x="cpm"
alias xc="cpm -c"
alias xd="cpm -d"
alias xm="cpm -m"
alias xp="cpm -p"

# BOOKMARKS - FILES
alias fb="jumpopen \$CONFIG .bashrc && . \$CONFIG/.bashrc"
alias fbl="\$EDITOR ~/.config/bashrc_local && . ~/.config/bashrc_local"
alias fgi="\$EDITOR \$(git rev-parse --show-toplevel)/.gitignore"
alias fgm="\$EDITOR \$(git rev-parse --show-toplevel)/.gitmodules"
alias fn="jumpopen \$CONFIG nvim/init.vim"
alias fp="jumpopen \$CONFIG .profile"
alias fr="\$EDITOR \$(git rev-parse --show-toplevel)/README.md"
alias fs="jumpopen \$CONFIG shrc && . \$CONFIG/shrc"
alias fu="nvim +'h user-manual | winc o'"
alias fx="jumpopen \$CONFIG sx/sxrc"
f() { if [ -d "$1" ]; then cd "$1" || return; else "$OPENER" "$@"; fi }
jumpopen() { cd "$1" >/dev/null && shift && "$OPENER" "$@" ; }

# BOOKMARKS - DATA
alias jd="cd ~/data"
alias jdc="cd ~/data/config/"
alias jde="cd ~/data/education"
alias jdj="cd ~/data && j"
alias jdp="cd ~/data/pictures"
alias jdu="cd ~/data/uni"

# BOOKMARKS - HIDDEN
bookmarks=$HOME/data/config/bookmarks
[ -f "$bookmarks" ] && . "$bookmarks"
alias bm="\$EDITOR \$bookmarks && . \$bookmarks"

# BOOKMARKS - HOME
alias dl="cd ~/Downloads"
alias jca="cd \$XDG_CACHE_HOME"
alias jch="cd \$XDG_CONFIG_HOME"
alias jl="cd \$HOME/.local"
alias jlb="cd \$HOME/.local/bin"
alias jls="cd \$XDG_DATA_HOME"

# BOOKMARKS - NOTES
alias jn="cd ~/data/notes"
alias n="jumpopen ~/data/notes notes.md"
alias nb="jumpopen ~/data/notes books.md"
alias ni="jumpopen ~/data/notes ideas.md"
alias nn="jumpopen ~/data/notes newsboat"
alias nr="jumpopen ~/data/notes research.md"
alias ns="jumpopen ~/data/notes sites.md"
alias rss="newsboat -u ~/data/notes/newsboat"

# BOOKMARKS - PROJECTS
alias faa="jumpopen ~/projects/arch desktop.sh base.sh"
alias fv="jumpopen ~/projects/vlugins README.md"
alias ja="cd ~/projects/arch"
alias jc="cd ~/projects/config"
alias jcf="cd ~/projects/config && f"
alias jp="cd ~/projects"
alias jpj="cd ~/projects && j"
alias js="cd ~/projects/scripts"
alias jsf="cd ~/projects/scripts && f"
alias jt="cd ~/projects/st"
alias jv="cd ~/projects/vlugins"
alias jw="cd ~/projects/saswm"

j() {
    dir=$1
    if [ $# = 0 ]; then
        dir=$(ffind -type d | fzf)
    elif [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    [ -n "$dir" ] && cd "$dir" || return
}

# GIT
k() { n=24; [ "$1" ] && n=$1; git log --all --graph --decorate --oneline --show-pulls -n"$n"; }
kcl() { git clone "$@" "$(xsel -b | head -n1)"; }
kg() { nvim +"Flog -search=$1"; }
krh() { n=1; [ "$1" ] && n=$1; git reset --hard HEAD~"$n"; }
ksf() { if [ $# = 0 ]; then git show | "$EDITOR"; else git show "$1" | "$EDITOR"; fi }

alias ka="git add"
alias kaa="git add --all"
alias kam="git commit --amend -v"
alias kap="git add -p"
alias kb="git branch -vv"
alias kba="git branch -avv"
alias kbd="git branch -D"
alias kbr="git remote -v | grep -P \(push\) | cut -d ' ' -f 1 | cut -f 2 | xargs -r \$BROWSER"
alias kd="git diff"
alias kfp="git format-patch --stdout HEAD^ >"
alias kk="nvim +Flog"
alias kr="cd \$(git rev-parse --show-toplevel)"
alias krv="git remote -v"
alias ks="git status -bs"
alias kt="git tag"

alias kc="git commit -v"
alias kca="git add --all && git commit -v"
alias kcp="git add --all && git commit -v && git push"
alias kcr="git commit -v -am tmp && git rebase -i HEAD~2"
alias kcrf="git commit -v -am tmp && git rebase -i HEAD~2 && git push -f"

alias ko="git checkout"
alias kop="git checkout -p"
alias kob="git checkout -b"
alias kom="git checkout master"

alias kf="git fetch"
alias kfr="git fetch \$(git remote | fzf)"
alias km="git merge"
alias kmm="git merge master"
alias kp="git push"
alias kpf="git push -f"
alias kpl="git pull"

alias kra="git rebase --abort"
alias krbr="git rebase -i --root"
alias krc="git rebase --continue"
alias krm="git rebase master"
krb() { n=16; [ "$1" ] && n=$1; git rebase -i HEAD~"$n"; }

alias kr.="git reset ."
alias krr="git reset --hard; git clean -f"
alias krs.="git reset --soft HEAD~1; git reset ."
alias krs="git reset --soft HEAD~1"
alias krv="git revert"

alias ksd="git stash drop"
alias ksl="git stash list"
alias ksp="git stash pop"
alias kst="git stash"

# MMRDF
alias m="mv -iv"
alias md="mkdir -pv"
mx() { touch "$1" && chmod +x "$1"; }
mf() {
    for arg in "$@"; do
        dir=$(dirname "$arg")
        [ ! -d "$dir" ] && mkdir -pv "$dir"
        touch "$arg" && echo touch: created file \'"$arg"\'
    done
}

# MISC
alias a="execute"
alias as="echo Remapped to do nothing."
alias b="cd - >/dev/null && ls"
alias c="cd .."
alias clean="sudo pacman -Rns \$(pacman -Qttdq); sudo pacman -Sc; rm -fr \$XDG_CACHE_HOME/*; sudo rm -fr /var/log/journal/*; rm -fr \$XDG_DATA_HOME/nvim/view/*"
alias da="d *"
alias dus="du -s"
alias e="\$EDITOR ."
alias g="grep -Rn"
alias gf="ffind | grep"
alias h="python"
alias i="pkg -i"
alias ig="iwctl station wlan0 get-networks"
alias ir="systemctl restart iwd.service"
alias is="iwctl station wlan0 scan"
alias l="preview"
alias lb="lsblk -o name,label,mountpoint,fstype,size"
alias ll="ls -l"
alias lt="lint"
alias m="mv"
alias o="autopen"
alias pa="patch -p1 <"
alias r="pkg -r"
alias re="sudo \$(fc -ln -1)"
alias s="echo \$(bstatus)% \| \$(pulsemixer --get-volume) \$(pulsemixer --get-mute) \| \$(date +%H:%M) \| \$(date +%d.%m.%y)"
alias sc="scrot -s"
alias td="tree -d"
alias tf="tree"
alias tmp="nvim +'set nospell' /tmp/scratch.md"
alias u="curl -s 'https://archlinux.org/mirrorlist/?protocol=https&use_mirror_status=on' | sed -e s/^#Server/Server/ -e /^#/d | sudo tee /etc/pacman.d/mirrorlist >/dev/null && paru"
alias v="pulsemixer"
ar() { dir="$(basename "$1").tar.gz"; [ $# -gt 1 ] && shift; tar -czvf "$dir" "$@"; }
cd() { command cd "$@" && ls; }
d() { if [ $# = 0 ]; then exit; else realpath -s "$@" | sed 's/.*/"&"/' | xargs rm -fr; ls; fi }
flash() { sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync; }
p() { if [ $# = 0 ]; then pwd | sed "s|$HOME|~|"; else cp -irv "$@"; fi }
y() { youtube-dl "$@" "$(xsel -b | head -n1)"; }

# TMUX
alias t="tmux new -A"
alias ta="tmux a -t"
alias tk="tmux kill-session -a"
alias tkt="tmux kill-session -t"
alias tl="tmux ls"
ts() { num=0; [ -n "$1" ] && num="$1"; tmux switch -t "$num"; }
tt() { echo "$TMUX_PANE" > /tmp/tmuxsend; }

# VIM
vpa() {
    [ $# = 0 ] && url="$(xsel -b | head -n1)" || url="$1"
    name=$(echo "$url" | sed s/.git$// | sed s/.n*vim$// | sed 's/.*\///' | sed s/^n*vim-//)
    git submodule add --force --name "$name" "$url" "nvim/pack/plugins/opt/$name"
}
vpd() {
    [ $# = 0 ] && echo No submodule provided. && return
    git rm -f "nvim/pack/plugins/opt/$1"
    rm -fr ".git/modules/$1"
}

# WALLPAPERS
alias jwl="cd ~/data/pictures/wallpapers"
alias wd="wal -d"
alias wn="cd ~/data/pictures/wallpapers && wal"
