#!/usr/bin/env sh

# DEFAULTS
alias cryptsetup="sudo cryptsetup"
alias df="df -h"
alias du="du -h"
alias fdisk="sudo fdisk"
alias gdisk="sudo gdisk"
alias grep="grep --color --exclude-dir=.?*"
alias ls="ls -Ahv --color --group-directories-first"
alias mount="sudo mount"
alias tree="tree -aCI '__pycache__|.git|*.aux|*.fdb_latexmk|*.fls|*.log|*.nav|*.snm|*.gz|*.toc' --dirsfirst --noreport"
alias umount="sudo umount"
alias watch="watch --color"

# CPM
alias x="cpm"
alias xc="cpm -c"
alias xd="cpm -d"
alias xm="cpm -m"
alias xp="cpm -p"

# BOOKMARKS - FILES
alias fb="jumpopen \$CONFIG .bashrc && . .bashrc"
alias fbl="\$EDITOR ~/.config/bashrc_local && . ~/.config/bashrc_local"
alias fn="jumpopen \$CONFIG nvim/init.vim"
alias fp="jumpopen \$CONFIG .profile && . .profile"
alias fr="\$EDITOR \$(git rev-parse --show-toplevel)/README.md"
alias fs="jumpopen \$CONFIG shrc && . shrc"
alias fu="nvim +'h user-manual | winc o'"
alias fx="jumpopen \$CONFIG sx/sxrc"
f() { if [ -d "$1" ]; then cd "$1" || return; else "$LAUNCHER" "$@"; fi }
jumpopen() { cd "$1" >/dev/null && shift && "$LAUNCHER" "$@" ; }

# BOOKMARKS - DATA
alias jd="cd ~/data"
alias jdc="cd ~/data/config/"
alias jde="cd ~/data/education"
alias jdj="cd ~/data && j"
alias jdp="cd ~/data/pictures"
alias jdu="cd ~/data/uni"

# BOOKMARKS - HIDDEN
bookmarks=$HOME/data/config/bookmarks
[ -f "$bookmarks" ] && . "$bookmarks"
alias bm="\$EDITOR \$bookmarks && . \$bookmarks"

# BOOKMARKS - HOME
alias dl="cd ~/Downloads"
alias jb="cd \$HOME/.local/bin"
alias jca="cd \$XDG_CACHE_HOME"
alias jco="cd \$XDG_CONFIG_HOME"
alias jl="cd \$HOME/.local"
alias jsh="cd \$XDG_DATA_HOME"

# BOOKMARKS - NOTES
alias jn="cd ~/data/notes"
alias n="jumpopen ~/data/notes notes"
alias nb="jumpopen ~/data/notes books"
alias ni="jumpopen ~/data/notes ideas"
alias nl="jumpopen ~/data/notes links"
alias nn="jumpopen ~/data/notes newsboat"
alias ns="jumpopen ~/data/notes study"
alias rss="newsboat -u ~/data/notes/newsboat"

# BOOKMARKS - REPOS
alias fa="jumpopen ~/repos/arch desktop.sh base.sh"
alias fv="jumpopen ~/repos/vlugins README.md"
alias ja="cd ~/repos/arch"
alias jc="cd ~/repos/config"
alias jcf="cd ~/repos/config && f"
alias jr="cd ~/repos"
alias jrj="cd ~/repos && j"
alias js="cd ~/repos/scripts"
alias jsf="cd ~/repos/scripts && f"
alias jt="cd ~/repos/st"
alias jv="cd ~/repos/vlugins"
alias jw="cd ~/repos/wm"

j() {
    dir=$1
    if [ $# = 0 ]; then
        dir=$(ffind -type d | fzf)
    elif [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    [ -n "$dir" ] && cd "$dir" || return
}

# GIT
k() { n=24; [ "$1" ] && n=$1; git log --all --graph --decorate --oneline --show-pulls -n"$n"; }
kcl() { git clone "$@" "$(xsel -b | head -n1)"; }
kg() { nvim -c "Flog -all -search=$1" -c 1tabclose; }
krh() { n=1; [ "$1" ] && n=$1; git reset --hard HEAD~"$n"; }
ksf() { if [ $# = 0 ]; then git show | "$EDITOR"; else git show "$1" | "$EDITOR"; fi }

alias ka="git add"
alias kaa="git add --all"
alias kam="git commit --amend -v"
alias kap="git add -p"
alias kb="git branch -vv"
alias kba="git branch -avv"
alias kbd="git branch -D"
alias kbr="git remote -v | grep -P \(push\) | cut -d ' ' -f 1 | cut -f 2 | xargs -r \$BROWSER"
alias kd="git diff"
alias kfp="git format-patch --stdout HEAD^ >"
alias kk="nvim -c 'Flog -all' -c 1tabclose"
alias kr="cd \$(git rev-parse --show-toplevel)"
alias krv="git remote -v"
alias ks="git status -bs"
alias kt="git tag"

alias kc="git commit -v"
alias kca="git add --all && git commit -v"
alias kcp="git add --all && git commit -v && git push"
alias kcr="git commit -v -am tmp && git rebase -i HEAD~2"
alias kcrf="git commit -v -am tmp && git rebase -i HEAD~2 && git push -f"

alias ko="git checkout"
alias kop="git checkout -p"
alias kob="git checkout -b"
alias kom="git checkout master"

alias kf="git fetch"
alias kfr="git fetch \$(git remote | fzf)"
alias km="git merge"
alias kmm="git merge master"
alias kp="git push"
alias kpf="git push -f"
alias kpl="git pull"

alias kra="git rebase --abort"
alias krbr="git rebase -i --root"
alias krc="git rebase --continue"
alias krm="git rebase master"
krb() { n=16; [ "$1" ] && n=$1; git rebase -i HEAD~"$n"; }

alias kr.="git reset ."
alias krr="git reset --hard; git clean -f"
alias krs.="git reset --soft HEAD~1; git reset ."
alias krs="git reset --soft HEAD~1"
alias krv="git revert"

alias ksd="git stash drop"
alias ksl="git stash list"
alias ksp="git stash pop"
alias kst="git stash"

# MMRDF
alias m="mv -iv"
alias md="mkdir -pv"
mx() { touch "$1" && chmod +x "$1"; }
mf() {
    for arg in "$@"; do
        dir=$(dirname "$arg")
        [ ! -d "$dir" ] && mkdir -pv "$dir"
        touch "$arg" && echo touch: created file \'"$arg"\'
    done
}

# MISC
alias .s=". \$XDG_CONFIG_HOME/shrc"
alias a="execute"
alias as="echo Remapped to do nothing."
alias b="cd - >/dev/null && ls"
alias c="cd .."
alias clean="sudo pacman -Rns \$(pacman -Qttdq); sudo pacman -Sc; rm -fr \$XDG_CACHE_HOME/*; sudo rm -fr /var/log/journal/*; rm -fr \$XDG_DATA_HOME/nvim/view/*"
alias da="d *"
alias dus="du -s"
alias e="\$EDITOR ."
alias g="grep -Rn"
alias gf="ffind | grep"
alias h="python"
alias i="pkg -i"
alias ig="iwctl station wlan0 get-networks"
alias ir="systemctl restart iwd.service"
alias is="iwctl station wlan0 scan"
alias l="preview"
alias lb="lsblk -o name,label,mountpoint,fstype,size"
alias ll="ls -l"
alias lt="lint"
alias m="mv"
alias pa="patch -p1 <"
alias r="pkg -r"
alias re="sudo \$(fc -ln -1)"
alias sc="scrot -s"
alias td="tree -d"
alias tf="tree"
alias tmp="nvim +'set nospell' /tmp/scratch.md"
alias u="curl -s 'https://archlinux.org/mirrorlist/?country=DE&protocol=https&use_mirror_status=on' | sed -e s/^#Server/Server/ -e /^#/d | sudo tee /etc/pacman.d/mirrorlist >/dev/null && paru"
alias v="pulsemixer"
ar() { dir="$(basename "$1").tar.gz"; [ $# -gt 1 ] && shift; tar -czvf "$dir" "$@"; }
cd() { command cd "$@" && ls; }
d() { if [ $# = 0 ]; then exit; else realpath -s "$@" | sed 's/.*/"&"/' | xargs rm -fr; ls; fi }
flash() { sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync; }
p() { if [ $# = 0 ]; then pwd | sed "s|$HOME|~|"; else cp -irv "$@"; fi }
s() { if [ $# = 0 ]; then echo "$(bstatus)% | $(pulsemixer --get-volume) | $(date +%H:%M) | $(date +%d.%m.%y)"; else googler --colors=eecghi -g us -l en "$@"; fi }
y() { youtube-dl "$@" "$(xsel -b | head -n1)"; }

# OPEN PROJECT-FILES
alias o="autopen"
alias ogi="\$EDITOR \$(git rev-parse --show-toplevel)/.gitignore"
alias ogm="\$EDITOR \$(git rev-parse --show-toplevel)/.gitmodules"
alias om="\$EDITOR Makefile"
alias or="[ -f "README*" ] && \$EDITOR README*"
alias os="\$EDITOR setup.sh"

autopen() {
    if [ -r main.* ]; then
        "$EDITOR" main.*
    elif [ -r setup.sh ]; then
        "$EDITOR" setup.sh
    elif [ -r config.h ]; then
        "$EDITOR" config.h
    else
        echo No appropriate file found.
    fi
}

# TMUX
alias t="tmux new -A"
alias ta="tmux a -t"
alias tk="tmux kill-session -a"
alias tkt="tmux kill-session -t"
alias tl="tmux ls"
ts() { num=0; [ -n "$1" ] && num="$1"; tmux switch -t "$num"; }
tt() { echo "$TMUX_PANE" > /tmp/tmuxsend; }

# VIM
vpa() {
    [ $# = 0 ] && url="$(xsel -b | head -n1)" || url="$1"
    name=$(echo "$url" | sed s/.git$// | sed s/.n*vim$// | sed 's/.*\///' | sed s/^n*vim-//)
    git submodule add --force --name "$name" "$url" "nvim/pack/plugins/opt/$name"
}
vpd() {
    [ $# = 0 ] && echo No submodule provided. && return
    git rm -f "nvim/pack/plugins/opt/$1"
    rm -fr ".git/modules/$1"
}

# WALLPAPERS
alias jwl="cd ~/data/pictures/wallpapers"
alias wd="wal -d"
alias wn="cd ~/data/pictures/wallpapers && wal"
