#!/usr/bin/env sh

export GTK_THEME=Arc-Dark

autorandr --change
bstatus -l &
dunst &
hsetroot -cover "$(cat ~/.local/share/wal)"
sxhkd &
xbanish &
xcompmgr &
xkbcomp "$XDG_CONFIG_HOME/xkb" "$DISPLAY"

while clipnotify; do xsel -bo | xsel -bi; done &

exec herbstluftwm -l
