#!/usr/bin/env sh

export GTK_THEME=Arc-Dark

autorandr --change
bstatus -l &
dunst &
hsetroot -cover "$(cat ~/.local/share/wal)"
sxhkd &
xbanish &
xcompmgr -cC -fD 3 &
xkbcomp "$XDG_CONFIG_HOME/xkb" "$DISPLAY"

exec herbstluftwm -l
