#!/usr/bin/env sh

# TODO: export in /etc/environment?
export _JAVA_AWT_WM_NONREPARENTING=1
export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

exec xswm
