#!/usr/bin/env sh

hc() { herbstclient "$@"; }

# PREPARE
hc emit_hook reload
hc keyunbind --all
altgr=Mod5
super=Mod4

# FRAMES & WINDOWS
hc keybind $altgr-a substitute WINID clients.focus.winid chain , cycle_all --skip-invisible +1 , bring WINID # move window to next frame
hc keybind $altgr-j spawn "$XDG_CONFIG_HOME/herbstluftwm/cycle.sh" +
hc keybind $altgr-k spawn "$XDG_CONFIG_HOME/herbstluftwm/cycle.sh" -
hc keybind $altgr-l cycle_frame
hc keybind $altgr-Shift-a substitute OLDWIN clients.focus.winid chain , cycle_frame , substitute NEWWIN clients.focus.winid spawn sh -c 'l=$(hc dump | sed "s,\\<$1\\>,0xTMP,;s,\\<$2\\>,$1,;s,\\<0xTMP\\>,$2,") ; hc load "$l"' -- OLDWIN NEWWIN # swap two windows between two frames
hc keybind $altgr-Shift-m mirror

# KILL
hc keybind $altgr-d close
hc keybind $altgr-Shift-r reload
hc keybind $altgr-Shift-s quit
hc keybind $super-d close

# MISC
hc set default_frame_layout 2
hc set focus_stealing_prevention 0
hc set tree_style '╾│ ├└╼─┐'

# MONITORS & TAGS
hc auto_detect_monitors
hc keybind $altgr-o use_index +1
hc keybind $altgr-Shift-o move_index +1
hc set swap_monitors_to_get_tag 0

# MOUSE
hc mouseunbind --all
hc mousebind $super-B1 move
hc mousebind $super-B3 resize
hc set focus_follows_mouse 1

# RESIZING
resizestep=0.03
hc keybind $altgr-Shift-h resize left $resizestep
hc keybind $altgr-Shift-l resize right $resizestep
hc keybind $altgr-i pseudotile toggle
hc keybind $super-x substitute FSRESTORE clients.focus.fullscreen chain , fullscreen on , attr clients.focus.ewmhrequests off , attr clients.focus.ewmhnotify toggle , spawn hc fullscreen FSRESTORE # fakefullscreen

# RULES
hc unrule -F
hc rule floating=off floatplacement=center focus=on index=0
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY)' pseudotile=on index=
hc rule windowtype='_NET_WM_WINDOW_TYPE_SPLASH' floating=on
hc rule title='win0' floating=on # jetbrains-splash-window
hc rule instance='tint2conf' pseudotile=off index=
hc rule instance='gcr-prompter' pseudotile=on index=
hc rule instance~'battery_status|launcher' floating=on
hc rule instance~'.*Nautilus|nemo|thunar|jetbrains-.*|JetBrains.*|code' index=1

# THEME
hc attr theme.floating.reset 1
hc attr theme.tiling.reset 1
hc attr theme.border_width 1
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set frame_gap 0
hc set window_gap -1

# INIT
if hc silent new_attr bool my_not_first_autostart ; then
    hc rename default 0
    hc add 1
    hc load 0 "(split horizontal:0.5:1 (clients max:0) (clients max:0))"
    hc load 1 "(clients max:0)"
    hc rule instance='st-256color' index=1 once
    hc spawn "$XDG_CONFIG_HOME"/autostart/autostart.sh
fi
hc unlock
