#!/usr/bin/env sh

# PREPARE
herbstclient emit_hook reload
herbstclient keyunbind --all
altgr=Mod5
super=Mod4

# FRAMES & WINDOWS
herbstclient keybind $altgr-a substitute WINID clients.focus.winid chain , cycle_all --skip-invisible +1 , bring WINID
herbstclient keybind $altgr-j cycle -1
herbstclient keybind $altgr-k cycle +1
herbstclient keybind $altgr-l cycle_frame

# KILL
herbstclient keybind $altgr-d close
herbstclient keybind $altgr-Shift-r reload
herbstclient keybind $altgr-Shift-s quit

# MISC
herbstclient set default_frame_layout 2
herbstclient set focus_stealing_prevention 0
herbstclient set tree_style '╾│ ├└╼─┐'

# MONITORS & TAGS
herbstclient auto_detect_monitors
herbstclient keybind $altgr-o use_index +1
herbstclient keybind $altgr-Shift-o move_index +1
herbstclient set swap_monitors_to_get_tag 0

# MOUSE
herbstclient mouseunbind --all
herbstclient mousebind $super-B1 move
herbstclient mousebind $super-B3 resize
herbstclient set focus_follows_mouse 1

# RESIZING
resizestep=0.03
herbstclient keybind $altgr-Shift-h resize left $resizestep
herbstclient keybind $altgr-Shift-l resize right $resizestep
herbstclient keybind $super-x substitute FSRESTORE clients.focus.fullscreen chain , fullscreen on , attr clients.focus.ewmhrequests off , attr clients.focus.ewmhnotify toggle , spawn herbstclient fullscreen FSRESTORE

# RULES
herbstclient unrule -F
herbstclient rule floating=off focus=on index=0
herbstclient rule instance='nemo' index=1
herbstclient rule instance='popup' pseudotile=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on

# THEME
herbstclient attr theme.floating.reset 1
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.border_width 1
herbstclient set frame_bg_transparent 1
herbstclient set frame_border_width 0
herbstclient set frame_gap 0
herbstclient set window_gap -1

# INIT
layout='(split horizontal:0.53:1 (clients max:0) (clients max:0))'
if herbstclient silent new_attr bool my_not_first_autostart ; then
    herbstclient rename default 0
    herbstclient add 1
    herbstclient load 0 "$layout"
    herbstclient load 1 "$layout"
    herbstclient rule instance~'st-256color' index=1 once
    herbstclient spawn "$BROWSER"
    herbstclient spawn "$TERMINAL" -e tmux new -A
fi
herbstclient unlock
