use_default_settings: true

search:
  safe_search : 1
  default_lang: "en"

server:
  secret_key : "ultrasecretkey"
  http_protocol_version: "1.1"

ui:
  advanced_search: on
  default_locale: "en"

outgoing:
  request_timeout: 16.0

engines:
  - name: youtube
    categories: videos
  - name: arch linux wiki
    disabled: true
  - name: artic
    disabled: true
  - name: arxiv
    disabled: true
  - name: askubuntu
    disabled: true
  - name: bandcamp
    disabled: true
  - name: bing
    disabled: true
  - name: bing images
    disabled: true
  - name: bing news
    disabled: true
  - name: bing videos
    disabled: true
  - name: brave
    disabled: true
  - name: btdigg
    disabled: true
  - name: ccengine
    disabled: true
  - name: crossref
    disabled: true
  - name: currency
    disabled: true
  - name: dailymotion
    disabled: true
  - name: deezer
    disabled: true
  - name: deviantart
    disabled: true
  - name: dictzone
    disabled: true
  - name: digg
    disabled: true
  - name: docker hub
    disabled: true
  - name: flickr
    disabled: true
  - name: genius
    disabled: true
  - name: gentoo
    disabled: true
  - name: github
    disabled: true
  - name: google news
    disabled: true
  - name: google scholar
    disabled: true
  - name: hoogle
    disabled: true
  - name: library of congress
    disabled: true
  - name: mankier
    disabled: true
  - name: mediathekviewweb
    disabled: true
  - name: microsoft academic
    disabled: true
  - name: mixcloud
    disabled: true
  - name: openairedatasets
    disabled: true
  - name: openairepublications
    disabled: true
  - name: pdbe
    disabled: true
  - name: photon
    disabled: true
  - name: piratebay
    disabled: true
  - name: pubmed
    disabled: true
  - name: pypi
    disabled: true
  - name: qwant
    disabled: true
  - name: qwant images
    disabled: true
  - name: qwant news
    disabled: true
  - name: qwant videos
    disabled: true
  - name: sepiasearch
    disabled: true
  - name: solidtorrents
    disabled: true
  - name: solidtorrents
    disabled: true
  - name: soundcloud
    disabled: true
  - name: stackoverflow
    disabled: true
  - name: superuser
    disabled: true
  - name: unsplash
    disabled: true
  - name: vimeo
    disabled: true
  - name: wikidata
    disabled: true
  - name: wikipedia
    disabled: true
  - name: wolframalpha
    disabled: true
  - name: yahoo news
    disabled: true
  - name: z-library
    disabled: true
